spring:
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 80

